# docker-compose run <nombreService> sh -c <comando>
# docker-compose up == Manda a correr la imagen con el comando principal

version: "3"

services: 
  app:
    build: 
      context: .
    ports: 
      - "5000:8000"
    volumes: 
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:5000"
    environment: 
      - DB_HOST=db 
      - DB_NAME=recipe
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on: 
      - db

  db:
    image: postgres:10-alpine3.14
    environment: 
      - POSTGRES_DB=recipe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    